version: "3.3"
services:
  database:
    image: "postgres:12.1-alpine"
    volumes:
      - ./tmp/database:/var/lib/postgresql/data
    env_file: .env

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/food-recipes
      - /food-recipes/node_modules/
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - database
