default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV.fetch("POSTGRES_USERNAME") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: food_recipes_development

test:
  <<: *default
  database: food_recipes_test
