default: &default
  adapter: postgresql
  encoding: unicode
  port: <%= ENV['DATABASE_PORT'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DATABASE_DEV'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_TEST'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>